title: <p align="center"> Himanshu Pandey</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/himanshu-pandey-46651313/">LinkedIn</a> |
  <a href="https://github.com/himsoftware">GitHub</a>
  
  <br>   
  I am Himanshu Kumar Pandey working as a Associate Architect with Capita India.
What I am describe about myself, its composition of dreams, passion, hard & smart work. Building software on open source Technology. I am very fond of new technology.
Specialties: ,NodeJS,MongoDB,,vuejs,vuex,element-ui ,vuetifyjs and graphql,devops-( Git lab,Git Hub,VSTS,Azure,container,docker implementation of CI/CD with BDD and TDD), very keen to use new tools like sublime,Atoms,gulp,express and nodemon,Visual Studio Code. More tools I am adding as a skill set Kubernetes, Azure Kubernetes, and architecting microservices. Designing DevOps for microservices and utilizes yml to deploy build code on Azure Kubernetes cluster. Experience with the Creation of Identity, AzureActive Directory(Creation of user over azure, manage them), RBAC, Monitoring (Creation Resource group management, Creation of Policy, Apply plociy over the group),IAAS. Experience in designing cloud-native based architecture implementation of PAAS based architecture( FunctionApp, Logic App, Appservices( docker based deployment and Slot implementation with blue green deployment). Core knowledge on Load balancing concept in Azure( Traffic Manager, Azure Front door, Load balancer, Application gateway) . Design the Cloud architecture that contain almost 10 virtual networks , Network security group , Virtual network peering, CIDR creation, subnet design . Each virtual Network multiple content and at different region . Implementation Azure database factory. Deep and hands-on knowledge on Azure Migrate Services. In Azure migrate tools is used for Assessment of resources on on-premises and enable to migrate over azure. In current project I am using Movere tools for migration purpose.
  <br>
  </p>



theme: jekyll-theme-minimal
