title: <p align="center"> Amar Raj Urs </p>
logo: /assets/img/ED38850D-ADDA-4A4C-89C6-61A0779AF0A8_1_201_a.heic
description: 
<p aligns"center"
<a here="https://www.linkedin.com/in/amarajurs/">LinkedIn<a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
