title: Pravin Pasi
logo: /assets/img/logo.png
description: 8+ Years of Experience in Back End Developent | Nodejs | C# | C++ | MySQl.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
