title: <p align="center"> Sheena Mathew</p>
logo: /assets/img/aimlenthu.jpg

description:
  <p align="center">
  <a href="https://github.com/SheenaMathew19">GitHub</a> |
  
  <br>   
   AI/ML enthusiast
  <br>
  </p>



theme: jekyll-theme-minimal
