title: Mallikarjunappa S S
logo: /assets/img/logo.png
description: I am working as a senior manager at Intel. Managing a team of around 20 members. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
