title: <p align="center"> Prashant Tandale </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/prashant-tandale-2a50623a">LinkedIn</a> |
  <a href="https://github.com/prashtandale">GitHub</a>
  
  </p>

theme: jekyll-theme-minimal
